AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://testdc333/75fcc1cc348b0a6495ebf9d8ad381359
      Environment:
        Variables:
          S3_BUCKET: testdc333
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
